### ISSUE TITLE
Windows: fork() function is unimplemented on this machine (NotImplementedError)

### ISSUE THREAD

**Issue by hxhxd** [thuehlinger/daemons#57]
Hello, I'm using ruby on windows, but daemons won't work because fork() is unimplemented on windows.
Is there a workaround for this?   
Thanks.  

```shell
D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/daemons-1.2.4/lib/daemons/daemonize.rb:10:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/daemons-1.2.4/lib/daemons/daemonize.rb:10:in `safefork'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/daemons-1.2.4/lib/daemons/daemonize.rb:45:in `call_as_daemon'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/daemons-1.2.4/lib/daemons/application.rb:270:in `start_proc'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/daemons-1.2.4/lib/daemons/application.rb:296:in `start'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/daemons-1.2.4/lib/daemons/controller.rb:56:in `run'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/daemons-1.2.4/lib/daemons.rb:197:in `block in run_proc'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/daemons-1.2.4/lib/daemons/cmdline.rb:92:in `catch_exceptions'
        from D:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/daemons-1.2.4/lib/daemons.rb:196:in `run_proc'
        from DynDNS.rb:15:in `<main>'
```

**Comment by thuehlinger** [comment]
If you are using a native Ruby distribution there is currently no workaround. You could however use Cygwin where fork() supported.

**Comment by hxhxd** [comment]
Yeah I'm using native Ruby distribution, and need keep using it for a while.
I've tried install Cygwin version but there're problems when both native/Cygwin  versions of Ruby installed.
I'll try Cygwin version only when native version no longer needed.
Thanks :)

**Comment by Timopheym** [comment]
Is there actualy no possability to find it? Even the thing that guys find out? 
https://github.com/vagrant-landrush/landrush/issues/16
There is actual hell with dependecies to move the whole list of packages from native version (i know i am stupid doing development on window)

**Comment by thuehlinger** [comment]
Hmmm, I guess we might be able to mimick the behavior using spawn (as in the reference you have given: https://github.com/hferentschik/landrush/commit/9523710f9771a08fd2b2d53f8de7373fca6c0860#diff-695e5af033f2e918c112401dcbf9bfb1R63)... Let me look into this a bit...

**Comment by entwanderer** [comment]
I would appreciate it, if there will be a solution in future. :-)
